# Generated by Django 3.2.25 on 2024-10-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('in_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('speed', models.IntegerField()),
                ('gb', models.IntegerField()),
                ('sms', models.IntegerField()),
                ('min', models.IntegerField()),
                ('number_of_channels', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_tariffs', to='app.city')),
                ('tariff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_tariffs', to='app.hometype')),
            ],
        ),
        migrations.CreateModel(
            name='MobileTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('gb', models.IntegerField()),
                ('sms', models.IntegerField()),
                ('min', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tariffs', to='app.city')),
            ],
        ),
    ]
